### ISSUE TITLE
problem test fft

### ISSUE THREAD

**Issue by djeanner** [cheminfo/multiplet-analysis#1]
Pas très important: 
Je ne comprends pas pourquoi dans mon test de fft, la ligne ci-dessous ne semble pas faire la fft. "re" revient de l'appel inchangé:
https://github.com/cheminfo/multiplet-analysis/blob/cc7cc16ffe1f8cac4c785bd7dc6fd5c900784c02/src/__tests__/FFT.fft.test.js#L55
Pourtant, je sais que fft fait ce que je veux  car dans un autre context cela marche :  
https://github.com/cheminfo/multiplet-analysis/blob/cc7cc16ffe1f8cac4c785bd7dc6fd5c900784c02/src/subroutine.js#L19
La différence est que l'appel à FFT.fft est dans une fonction dans le second cas, et dans le test lui-même dans le premier. J'ai essayé "async" sans succès.

**Comment by lpatiny** [comment]
I checked FFT documentation and apparently we need to initialize the FFT.

```js
    FFT.init(4);
```

Does not seems so intuitive and I filled a change request: https://github.com/mljs/fft/issues/5
