### ISSUE TITLE
Chemical shift

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/multiplet-analysis#17]
I'm currently implementing with the multiplet-analyser in the nmr-displayer and I have a stupid problem ... in the result I don't have the chemical shift !

Would it be possible that this method returns:
```
{
  delta: 7.12,
  j: ]|
}
```

**Comment by djeanner** [comment]
I don't have time now - but it should be easy to fix...
As Now, here is the code generatting the results:
              result.j.push({
                multiplicity: 'd',
                coupling: topPosJ * resolutionHz,
              });
Line 229 in index.js.
It des not return the chemical shift. We could just return the position of the top position (or center of mass of the final signal). This could be inserted just before `return results` at line 281 in src/index.js. The final shape is in `spe` and the corresponding scale is in `sca`, jet get the index from the first and get the chemical shift from the second.

**Comment by djeanner** [comment]
I return a chemical shift. Still I don't understand the very first return of the methods  (in the first box of this Issue).
