### ISSUE TITLE
Feature request: loop over multiplets

### ISSUE THREAD

**Issue by djeanner** [cheminfo/multiplet-analysis#2]
In index.html, instead of ploting only one multiplet (multiplet1.json) and one error function (errfun1.json), plot for all number until no more (multiplet2.json ...). Finally plot the lineshape.json (as a last multiplet).

**Comment by lpatiny** [comment]
If you need more information or more graph just add the in the result.debug using the `appendDebug` method.

I will take care to plot the data you need (annotations or whatever)


![image](https://user-images.githubusercontent.com/1484241/73592621-93c79780-44fc-11ea-96da-7177b03c00d6.png)
