### ISSUE TITLE
problem calling maxY function

### ISSUE THREAD

**Issue by djeanner** [cheminfo/multiplet-analysis#23]
I don't know how to feed the function with the correct names for the object. 
I want to replace my old code with the new one which is currently commented here https://github.com/cheminfo/multiplet-analysis/blob/37b188a0ed119dd0510362dbd514abd72ffa8637/src/index.js#L275

**Comment by lpatiny** [comment]
The method maxX described here:
https://github.com/mljs/array-xy/tree/master/packages/ml-array-xy-max-y
requires that you send an object 'points' that contains 2 properties:
- x: an array
- y: an array


This means that in your case you should do something like:
  const points = { sca, spe };
  let MaxSpe = maxY({x:sca, y:spe});

Please also try to use camelCase and for an instance of a variable always a lower case as first character. So please use 'maxSpe'.

We also like to use long names to make it easier to maintain the code. So we don't hesitate to use 'maxSpectraHeight' or whatever (I don't know what is this variable).

You can rename variable in vscode by clicking on a variable and hitting `F2`.
