### ISSUE TITLE
multiple plot graph

### ISSUE THREAD

**Issue by djeanner** [cheminfo/multiplet-analysis#3]
Instead of plotting only one line, I would like to plot multiple lines (in the multiplet and error function windows). In other words, instead of having x and y, in multiplet1.json and errfun1.json, I would like to have and array of array, or x1, y1, y2, y2, etc.

**Comment by djeanner** [comment]
Recursive simplification of the multiplet structure. Each step provides a coupling. Here a cross-section in the high-resolution DQF-COSY spectrum with multiple ++ splitting and one +- splitting (for the active coupling - the one between the spins giving rise to the cross-peak under investigation. Bottom: fragment of the coupling obtained by the analysis of this cross peak. Whe working with 1d <sup>1</sup>H multiplets, the fragment will not designate the partner, only the four edges. Ref: http://archive-ouverte.unige.ch/unige:7891
[direct ref](https://onlinelibrary.wiley.com/doi/abs/10.1002/%28SICI%291097-458X%28200003%2938%3A3%3C156%3A%3AAID-MRC610%3E3.0.CO%3B2-R)
![Screenshot 2020-01-31 10 25 48](https://user-images.githubusercontent.com/26463431/73527862-1163a880-4414-11ea-9578-56a3243a30d2.png)

**Comment by lpatiny** [comment]
We create now only one result.json

**Comment by lpatiny** [comment]
In order to run the code please use
`node -r esm examples/double.js`
The `web` folder is also now in examples.
