### ISSUE TITLE
scale problem when zooming into the error function

### ISSUE THREAD

**Issue by djeanner** [cheminfo/multiplet-analysis#4]
In the page generated by https://github.com/cheminfo/multiplet-analysis/blob/master/web/index.html 

When zooming in the multiplet (left), everything is OK:
![Screenshot 2020-01-30 08 52 02](https://user-images.githubusercontent.com/26463431/73430273-ee66c500-433d-11ea-9abd-6b20e62d56d4.png)

But zooming in the error function (right), the scale goes crazy:

![Screenshot 2020-01-30 08 52 09](https://user-images.githubusercontent.com/26463431/73430278-f161b580-433d-11ea-9617-2a6767b51f39.png)

I may not have duplicated correctly the graphs... Should be fixed before adding the loops of the two other issues.

**Comment by lpatiny** [comment]
fixed in cadd9316bbd3b796b7d3cc225d835f4860604a59
